#!/usr/bin/env bash

source "$repository_root/tests/mcsmv21_native_link_sources.sh"

mcsmv22_native_link_sources=(
	"${mcsmv21_native_link_sources[@]}"
	"$repository_root/src/geometry/service/TriangleGeometryRelationshipService.cpp"
	"$repository_root/src/geometry/service/MeshSurfaceDistanceEvaluationService.cpp"
	"$repository_root/src/geometry/service/MeshIntersectionScreeningService.cpp"
	"$repository_root/src/geometry/service/MeshRayParityClassificationService.cpp"
	"$repository_root/src/geometry/service/RigidTransformValidationService.cpp"
	"$repository_root/src/geometry/service/MeshRigidTransformationService.cpp"
	"$repository_root/src/geometry/service/ConvexHullMeshGenerationService.cpp"
	"$repository_root/src/geometry/service/StlMeshLoadingService.cpp"
	"$repository_root/src/vehicle/model/VehicleJointGraph.cpp"
	"$repository_root/src/vehicle/service/VehicleSuspensionKinematicEvaluationService.cpp"
	"$repository_root/src/vehicle/service/VehicleReferenceFrameTransformationService.cpp"
	"$repository_root/src/vehicle/service/VehicleTyreMeshGenerationService.cpp"
	"$repository_root/src/vehicle/service/VehicleTyrePoseTransformationService.cpp"
	"$repository_root/src/vehicle/service/VehicleTyreSweepValidationService.cpp"
	"$repository_root/src/vehicle/service/VehicleClosureMotionEvaluationService.cpp"
	"$repository_root/src/vehicle/service/VehicleClosureSweepValidationService.cpp"
	"$repository_root/src/vehicle/service/VehicleGlassMotionValidationService.cpp"
	"$repository_root/src/vehicle/mcsmv2/service/McsMv22KinematicCatalogFactory.cpp"
	"$repository_root/src/vehicle/mcsmv2/service/McsMv22NativePartitionGeometryLoadingService.cpp"
	"$repository_root/src/vehicle/mcsmv2/service/McsMv22NativeKinematicEvidenceLoadingService.cpp"
	"$repository_root/src/vehicle/mcsmv2/service/McsMv22SemanticKinematicBindingService.cpp"
	"$repository_root/src/vehicle/mcsmv2/service/McsMv22SuspensionKinematicEvaluationService.cpp"
	"$repository_root/src/vehicle/mcsmv2/service/McsMv22ClosureKinematicEvaluationService.cpp"
	"$repository_root/src/vehicle/mcsmv2/service/McsMv22KinematicAssuranceEvaluationService.cpp"
	"$repository_root/src/vehicle/mcsmv2/service/McsMv22KinematicGeometryGenerationService.cpp"
	"$repository_root/src/vehicle/mcsmv2/service/McsMv22KinematicPoseEvaluationService.cpp"
	"$repository_root/src/vehicle/mcsmv2/service/McsMv22GeneratedMeshProvider.cpp"
	"$repository_root/src/vehicle/mcsmv2/service/McsMv22KinematicGrammarLoweringService.cpp"
)
